# code: language=ansible
---
- name: "Make directory structure"
  ansible.builtin.include_tasks: make_directory_structure.yml

- name: "Make openssl configs"
  ansible.builtin.include_tasks: make_openssl_configs.yml
  loop: "{{ common_names }}"

- name: "Generate CSRs and keys"
  ansible.builtin.include_tasks: generate_csrs_and_keys.yml
  loop: "{{ common_names }}"
