# code: language=ansible
---
- name: "Generate openssl configs, CSRs and keys from the list of FQRNs"
  hosts: localhost
  vars:
    common_names:
      - cn: "vasyan.nokogerra.lab"
      - cn: "*.wildcard.com"
      - cn: taras.nokogerra.lab
        sans:
          - "DNS.1 = taras.nokogerra.lab"
          - "DNS.2 = one.taras.nokogerra.lab"
          - "DNS.3 = one.taras.nokogerra.lab"
          - "IP.1 = 1.1.1.1"
          - "IP.2 = 2.2.2.2"
  roles:
    - generate_csr_and_key_from_list
