# code: language=ansible
---
country: "RU"
state: "Moscow"
location: "Moscow"
organization: "The Ministry of Digital Development and Communications"
key_length: "2048"
key_usage: "digitalSignature, keyEncipherment"
ext_key_usage: "serverAuth"
common_names:
  - cn: "vasyan.nokogerra.lab"
  - cn: "*.wildcard.com"
  - cn: taras.nokogerra.lab
    sans:
      - "DNS.1 = taras.nokogerra.lab"
      - "DNS.2 = one.taras.nokogerra.lab"
      - "DNS.3 = one.taras.nokogerra.lab"
      - "IP.1 = 1.1.1.1"
      - "IP.2 = 2.2.2.2"
